In [9]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [10]:
## Load model file
ann_model=load_model('model.h5')

## Load Encoder
with open('labelencoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('OneHotEncoder_geo.pkl','rb') as file:
    geo_encoder=pickle.load(file)


## load Scale
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [11]:
# Example input data
input_data = [{
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}]

In [12]:
df=pd.DataFrame(input_data)

In [13]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [ ]:
geo_encoded=geo_encoder.transform(df[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=geo_encoder.get_feature_names_out(['Geography']))
df=df.drop(["Geography"],axis=1)
df=pd.concat([df,geo_encoded_df],axis=1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [15]:
df['Gender']=label_encoder_gender.transform(df['Gender'])

In [17]:
df=scaler.transform(df)

In [20]:
prediction=ann_model.predict(df)

1/1 [==============================] - 0s 32ms/step

In [21]:
print(prediction)

[[0.04580542]]