In [143]:
import pandas as pd
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
import pickle

In [144]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [145]:
lableEncoderGender=LabelEncoder()
df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)
df['Gender']=lableEncoderGender.fit_transform(df['Gender'])

In [146]:
OneHotEncoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=OneHotEncoder_geo.fit_transform(df[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=OneHotEncoder_geo.get_feature_names_out(['Geography']))

In [147]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [148]:
df=pd.concat([df.drop(['Geography'],axis=1),geo_encoded_df],axis=1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [149]:
lableEncoderGender=LabelEncoder()
df['Gender']=lableEncoderGender.fit_transform(df['Gender'])
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [151]:
from sklearn.model_selection import train_test_split
X_train=df.drop(['EstimatedSalary'],axis=1)

y=df['EstimatedSalary']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [152]:
scaler=StandardScaler()
columns=X_train.columns.to_list()


X_train=pd.DataFrame(scaler.fit_transform(X_train),columns=columns)

In [153]:
with open('scaler_regression.pkl','wb') as file:
    pickle.dump(scaler,file)
with open('label_encoder_regression.pkl','wb') as file:
    pickle.dump(lableEncoderGender,file)
with open('oneHot_regression.pkl','wb') as file:
    pickle.dump(OneHotEncoder_geo,file)

In [154]:
X
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [155]:
#Ann Regression
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [156]:
ann_model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='linear')#linear is default
])

ann_model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
ann_model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 64)                832

 dense_10 (Dense)            (None, 32)                2080

 dense_11 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [157]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime
#setup Tensor Board
log_dir="regression_log/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [158]:
ts_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [159]:
early_stop_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [160]:
ann_model.fit(X_train,y_train,
              validation_data=(X_test,y_test),
              epochs=100,
              callbacks=[ts_callback,early_stop_callback])

Epoch 1/100
WARNING:tensorflow:From c:\Users\hp\MachineLearning\mlvenv\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\hp\MachineLearning\mlvenv\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 4ms/step - loss: 100383.4219 - mae: 100383.4219 - val_loss: 98618.7031 - val_mae: 98618.7031
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99861.7812 - mae: 99861.7812 - val_loss: 97560.2031 - val_mae: 97560.2031
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 98026.1094 - mae: 98026.1094 - val_loss: 94821.2422 - val_mae: 94821.2422
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 94337.9297 - mae: 94337.9297 - val_loss: 90082.2891 - val_mae: 90082.2891
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 88754.0312 - mae: 88754.0312 - val_loss: 83516.9297 - val_mae: 83516.9297
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 81661.2969 - mae: 81661.2969 - val_loss: 75844.5781 - val_mae: 75844.5781
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 73922.5391 - mae: 73922.5391 - val_loss: 68116.3828 - val_mae: 68116.3828
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 66594.7734 - mae: 66594.7734 - val_loss: 61179.4023 - val_mae: 61179.4023
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 60456.4531 - mae: 60456.4531 - val_loss: 55953.4453 - val_mae: 55953.4453
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 56008.9570 - mae: 56008.9570 - val_loss: 52531.2891 - val_mae: 52531.2891
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 53170.7812 - mae: 53170.7812 - val_loss: 50768.8125 - val_mae: 50768.8125
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 51709.0039 - mae: 51709.0039 - val_loss: 50093.2461 - val_mae: 50093.2461
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 51028.2891 - mae: 51028.2891 - val_loss: 49877.0469 - val_mae: 49877.0469
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50726.6523 - mae: 50726.6523 - val_loss: 49812.3164 - val_mae: 49812.3164
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50566.5664 - mae: 50566.5664 - val_loss: 49803.8398 - val_mae: 49803.8398
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50477.2773 - mae: 50477.2773 - val_loss: 49783.1523 - val_mae: 49783.1523
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50407.6953 - mae: 50407.6953 - val_loss: 49768.5273 - val_mae: 49768.5273
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50345.1328 - mae: 50345.1328 - val_loss: 49758.3438 - val_mae: 49758.3438
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50293.4922 - mae: 50293.4922 - val_loss: 49731.7891 - val_mae: 49731.7891
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 50244.6914 - mae: 50244.6914 - val_loss: 49723.0469 - val_mae: 49723.0469
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 50199.3516 - mae: 50199.3516 - val_loss: 49721.9531 - val_mae: 49721.9531
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 50159.9336 - mae: 50159.9336 - val_loss: 49696.3945 - val_mae: 49696.3945
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 50125.9023 - mae: 50125.9023 - val_loss: 49685.0977 - val_mae: 49685.0977
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 50091.9453 - mae: 50091.9453 - val_loss: 49669.8398 - val_mae: 49669.8398
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 50067.9766 - mae: 50067.9766 - val_loss: 49643.1055 - val_mae: 49643.1055
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 50041.3047 - mae: 50041.3047 - val_loss: 49656.3125 - val_mae: 49656.3125
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 50017.3242 - mae: 50017.3242 - val_loss: 49648.3672 - val_mae: 49648.3672
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49996.3086 - mae: 49996.3086 - val_loss: 49635.6055 - val_mae: 49635.6055
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49981.1953 - mae: 49981.1953 - val_loss: 49630.2188 - val_mae: 49630.2188
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49959.5078 - mae: 49959.5078 - val_loss: 49617.9297 - val_mae: 49617.9297
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49941.9023 - mae: 49941.9023 - val_loss: 49620.2461 - val_mae: 49620.2461
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49926.8555 - mae: 49926.8555 - val_loss: 49605.7578 - val_mae: 49605.7578
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49912.6055 - mae: 49912.6055 - val_loss: 49601.0977 - val_mae: 49601.0977
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49900.3555 - mae: 49900.3555 - val_loss: 49598.7656 - val_mae: 49598.7656
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49888.3086 - mae: 49888.3086 - val_loss: 49593.9102 - val_mae: 49593.9102
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 49877.6680 - mae: 49877.6680 - val_loss: 49579.5938 - val_mae: 49579.5938
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49863.8242 - mae: 49863.8242 - val_loss: 49569.6523 - val_mae: 49569.6523
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49856.2617 - mae: 49856.2617 - val_loss: 49558.0547 - val_mae: 49558.0547
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 49845.2070 - mae: 49845.2070 - val_loss: 49536.1875 - val_mae: 49536.1875
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49836.8672 - mae: 49836.8672 - val_loss: 49538.5391 - val_mae: 49538.5391
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49828.2617 - mae: 49828.2617 - val_loss: 49531.0156 - val_mae: 49531.0156
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49819.2734 - mae: 49819.2734 - val_loss: 49531.6055 - val_mae: 49531.6055
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49813.6289 - mae: 49813.6289 - val_loss: 49520.8125 - val_mae: 49520.8125
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49802.7891 - mae: 49802.7891 - val_loss: 49529.6016 - val_mae: 49529.6016
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49795.8047 - mae: 49795.8047 - val_loss: 49524.6016 - val_mae: 49524.6016
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49787.0430 - mae: 49787.0430 - val_loss: 49508.9375 - val_mae: 49508.9375
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 49782.2422 - mae: 49782.2422 - val_loss: 49518.7031 - val_mae: 49518.7031
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49775.6016 - mae: 49775.6016 - val_loss: 49517.1797 - val_mae: 49517.1797
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49769.6406 - mae: 49769.6406 - val_loss: 49508.7539 - val_mae: 49508.7539
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49761.3750 - mae: 49761.3750 - val_loss: 49496.4531 - val_mae: 49496.4531
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49755.8789 - mae: 49755.8789 - val_loss: 49492.8086 - val_mae: 49492.8086
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49750.7812 - mae: 49750.7812 - val_loss: 49499.3477 - val_mae: 49499.3477
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49744.2695 - mae: 49744.2695 - val_loss: 49494.1172 - val_mae: 49494.1172
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49741.6289 - mae: 49741.6289 - val_loss: 49487.4648 - val_mae: 49487.4648
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49735.1797 - mae: 49735.1797 - val_loss: 49478.2070 - val_mae: 49478.2070
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49731.6211 - mae: 49731.6211 - val_loss: 49466.8633 - val_mae: 49466.8633
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49726.2227 - mae: 49726.2227 - val_loss: 49465.6641 - val_mae: 49465.6641
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49718.2734 - mae: 49718.2734 - val_loss: 49474.6914 - val_mae: 49474.6914
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 49712.1797 - mae: 49712.1797 - val_loss: 49465.0898 - val_mae: 49465.0898
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49712.5391 - mae: 49712.5391 - val_loss: 49466.3164 - val_mae: 49466.3164
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 49704.2188 - mae: 49704.2188 - val_loss: 49454.8320 - val_mae: 49454.8320
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 49702.1406 - mae: 49702.1406 - val_loss: 49467.5352 - val_mae: 49467.5352
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 49694.9492 - mae: 49694.9492 - val_loss: 49460.9805 - val_mae: 49460.9805
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 49692.6797 - mae: 49692.6797 - val_loss: 49454.4688 - val_mae: 49454.4688
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 49688.3320 - mae: 49688.3320 - val_loss: 49456.9414 - val_mae: 49456.9414
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 49680.8945 - mae: 49680.8945 - val_loss: 49462.2188 - val_mae: 49462.2188
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 49682.2305 - mae: 49682.2305 - val_loss: 49445.6406 - val_mae: 49445.6406
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 49678.1484 - mae: 49678.1484 - val_loss: 49435.8867 - val_mae: 49435.8867
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 49673.4531 - mae: 49673.4531 - val_loss: 49424.5664 - val_mae: 49424.5664
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 49668.2227 - mae: 49668.2227 - val_loss: 49447.4414 - val_mae: 49447.4414
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 49665.7656 - mae: 49665.7656 - val_loss: 49446.6250 - val_mae: 49446.6250
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 49661.4062 - mae: 49661.4062 - val_loss: 49435.3555 - val_mae: 49435.3555
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 49658.3555 - mae: 49658.3555 - val_loss: 49448.1914 - val_mae: 49448.1914
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 49656.1914 - mae: 49656.1914 - val_loss: 49455.0508 - val_mae: 49455.0508

In [161]:
y_train.shape

(8000,)

In [162]:
%load_ext tensorboard

In [165]:
%tensorboard --logdir regression_log/fit

Reusing TensorBoard on port 6006 (pid 12236), started 0:00:13 ago. (Use '!kill 12236' to kill it.)

In [168]:
test_loss,test_mae=ann_model.evaluate(X_test,y_test)
test_mae

63/63 [==============================] - 0s 2ms/step - loss: 49424.5664 - mae: 49424.5664

49424.56640625

In [169]:
## Saving model
ann_model.save('regression_model.h5')

c:\Users\hp\MachineLearning\mlvenv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(